Fatal | CKSource.CKFinder.Connector.Core.CommandHandler | 2018-08-28 10:05:44.0214 | An unknown error has occured during execution of Proxy command.| System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKSource.FileSystem.Local.LocalStorage.<FolderExistsAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKSource.CKFinder.Connector.Core.Nodes.Folder.<ExistsAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKSource.CKFinder.Connector.Core.Nodes.NodeValidator.<ThrowIfReadDeniedAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKSource.CKFinder.Connector.Core.Nodes.NodeValidator.<ThrowIfReadDeniedAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKSource.CKFinder.Connector.Core.Commands.Proxy.ProxyCommandImpl.<ExecuteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKSource.CKFinder.Connector.Core.CommandHandler.<ExecuteAsync>d__12.MoveNext()    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKSource.FileSystem.Local.LocalStorage.<FolderExistsAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKSource.CKFinder.Connector.Core.Nodes.Folder.<ExistsAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKSource.CKFinder.Connector.Core.Nodes.NodeValidator.<ThrowIfReadDeniedAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKSource.CKFinder.Connector.Core.Nodes.NodeValidator.<ThrowIfReadDeniedAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKSource.CKFinder.Connector.Core.Commands.Proxy.ProxyCommandImpl.<ExecuteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKSource.CKFinder.Connector.Core.CommandHandler.<ExecuteAsync>d__12.MoveNext()
Error | CKSource.CKFinder.Connector.Core.CommandHandler | 2018-08-28 12:18:30.0629 | The Proxy command has failed - InvalidType (Resource Images?tFolder=/Microcentrifuge/ClearLock/ is not registered).
Error | CKSource.CKFinder.Connector.Core.CommandHandler | 2018-08-28 12:18:30.0629 | The Proxy command has failed - InvalidType (Resource Images?tFolder=/Microcentrifuge/ClearLock/ is not registered).
Error | CKSource.CKFinder.Connector.Core.CommandHandler | 2018-08-28 12:18:30.0629 | The Proxy command has failed - InvalidType (Resource Images?tFolder=/Microcentrifuge/ClearLock/ is not registered).
Error | CKSource.CKFinder.Connector.Core.CommandHandler | 2018-08-28 12:18:30.1098 | The Proxy command has failed - InvalidType (Resource Images?tFolder=/Microcentrifuge/ClearLock/ is not registered).
Error | CKSource.CKFinder.Connector.Core.CommandHandler | 2018-08-28 12:18:30.2191 | The Proxy command has failed - InvalidType (Resource Images?tFolder=/Microcentrifuge/ClearLock/ is not registered).
Error | CKSource.CKFinder.Connector.Core.CommandHandler | 2018-08-28 12:18:30.2191 | The Proxy command has failed - InvalidType (Resource Images?tFolder=/Microcentrifuge/ClearLock/ is not registered).
Error | CKSource.CKFinder.Connector.Core.CommandHandler | 2018-08-28 12:18:30.2191 | The Proxy command has failed - InvalidType (Resource Images?tFolder=/Microcentrifuge/ClearLock/ is not registered).
Error | CKSource.CKFinder.Connector.Core.CommandHandler | 2018-08-28 12:19:23.2720 | The Proxy command has failed - InvalidType (Resource Images?tFolder=/Microcentrifuge/ClearLock/ is not registered).
Error | CKSource.CKFinder.Connector.Core.CommandHandler | 2018-08-28 12:19:23.2720 | The Proxy command has failed - InvalidType (Resource Images?tFolder=/Microcentrifuge/ClearLock/ is not registered).
Error | CKSource.CKFinder.Connector.Core.CommandHandler | 2018-08-28 12:19:23.2877 | The Proxy command has failed - InvalidType (Resource Images?tFolder=/Microcentrifuge/ClearLock/ is not registered).
Error | CKSource.CKFinder.Connector.Core.CommandHandler | 2018-08-28 12:19:23.3345 | The Proxy command has failed - InvalidType (Resource Images?tFolder=/Microcentrifuge/ClearLock/ is not registered).
Error | CKSource.CKFinder.Connector.Core.CommandHandler | 2018-08-28 12:19:23.4596 | The Proxy command has failed - InvalidType (Resource Images?tFolder=/Microcentrifuge/ClearLock/ is not registered).
Error | CKSource.CKFinder.Connector.Core.CommandHandler | 2018-08-28 12:19:23.4596 | The Proxy command has failed - InvalidType (Resource Images?tFolder=/Microcentrifuge/ClearLock/ is not registered).
Error | CKSource.CKFinder.Connector.Core.CommandHandler | 2018-08-28 12:19:23.4596 | The Proxy command has failed - InvalidType (Resource Images?tFolder=/Microcentrifuge/ClearLock/ is not registered).
Fatal | CKSource.CKFinder.Connector.Core.CommandHandler | 2018-08-28 13:18:22.7968 | An unknown error has occured during execution of Proxy command.| System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKSource.FileSystem.Local.LocalStorage.<FolderExistsAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKSource.CKFinder.Connector.Core.Nodes.Folder.<ExistsAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKSource.CKFinder.Connector.Core.Nodes.NodeValidator.<ThrowIfReadDeniedAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKSource.CKFinder.Connector.Core.Nodes.NodeValidator.<ThrowIfReadDeniedAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKSource.CKFinder.Connector.Core.Commands.Proxy.ProxyCommandImpl.<ExecuteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKSource.CKFinder.Connector.Core.CommandHandler.<ExecuteAsync>d__12.MoveNext()    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKSource.FileSystem.Local.LocalStorage.<FolderExistsAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKSource.CKFinder.Connector.Core.Nodes.Folder.<ExistsAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKSource.CKFinder.Connector.Core.Nodes.NodeValidator.<ThrowIfReadDeniedAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKSource.CKFinder.Connector.Core.Nodes.NodeValidator.<ThrowIfReadDeniedAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKSource.CKFinder.Connector.Core.Commands.Proxy.ProxyCommandImpl.<ExecuteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKSource.CKFinder.Connector.Core.CommandHandler.<ExecuteAsync>d__12.MoveNext()
Fatal | CKSource.CKFinder.Connector.Core.CommandHandler | 2018-08-28 13:18:22.7968 | An unknown error has occured during execution of Proxy command.| System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKSource.FileSystem.Local.LocalStorage.<ReadAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKSource.CKFinder.Connector.Core.Nodes.File.<ReadAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKSource.CKFinder.Connector.Core.Commands.Proxy.ProxyCommandImpl.<ExecuteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKSource.CKFinder.Connector.Core.CommandHandler.<ExecuteAsync>d__12.MoveNext()    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKSource.FileSystem.Local.LocalStorage.<ReadAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKSource.CKFinder.Connector.Core.Nodes.File.<ReadAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKSource.CKFinder.Connector.Core.Commands.Proxy.ProxyCommandImpl.<ExecuteAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKSource.CKFinder.Connector.Core.CommandHandler.<ExecuteAsync>d__12.MoveNext()
